services:
  ramuza-frontend:
    build:
      context: ../frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://ramuza-backend:3000/api/v1
    depends_on:
      - ramuza-backend

  ramuza-backend:
    build:
      context: ../backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ramuza:ramuza@postgres:5432/ramuza_nexus?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
    depends_on:
      - postgres
      - redis

  ramuza-worker:
    build:
      context: ../worker
    environment:
      DATABASE_URL: postgresql://ramuza:ramuza@postgres:5432/ramuza_nexus?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ramuza
      POSTGRES_PASSWORD: ramuza
      POSTGRES_DB: ramuza_nexus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres-data:
