// Catálogo dos parâmetros SPEC descritos no Manual do Usuário Atena II (§2.1, "Tabela do SPEC").
// Cada item é apenas a referência (número + descrição curta + valor padrão de fábrica);
// o valor efetivo por cliente fica salvo em SpecParametro (banco).
export interface SpecCatalogItem {
  numero: number;
  descricao: string;
  valorPadrao?: string;
}

export const SPEC_CATALOG: SpecCatalogItem[] = [
  { numero: 0, descricao: "B1: Formato de etiqueta (0~99)", valorPadrao: "10" },
  { numero: 1, descricao: "B1: Formato do código de barras (0~29)", valorPadrao: "10" },
  { numero: 2, descricao: "B1: Bandeira do código de barras (0~99999)", valorPadrao: "2" },
  { numero: 3, descricao: "B1: Quantidade de etiquetas impressas (0~99)", valorPadrao: "1" },
  { numero: 4, descricao: "B1: Inversão do código de barras (0 normal, 1 inverso)", valorPadrao: "0" },
  { numero: 5, descricao: "B1: Formato da etiqueta acumulada (0~99)", valorPadrao: "13" },
  { numero: 6, descricao: "B1: Código de barras acumulada (0~29)" },
  { numero: 7, descricao: "B1: Bandeira do código de barras acumulada (0~99999)", valorPadrao: "2" },
  { numero: 8, descricao: "B1: Tempo de impressão acumulada (0~99)" },
  { numero: 9, descricao: "B1: Reservado a impressão acumulada" },
  { numero: 20, descricao: "Velocidade de impressão (0~99)", valorPadrao: "33" },
  { numero: 21, descricao: "Tipo de etiqueta (0 contínua, 1 comum)", valorPadrao: "1" },
  { numero: 22, descricao: "Contraste de impressão da etiqueta comum (0~15)", valorPadrao: "7" },
  { numero: 23, descricao: "Contraste de impressão da etiqueta contínua (0~15)", valorPadrao: "7" },
  { numero: 24, descricao: "Papel contínuo: intervalo de cada impressão (0~99mm)", valorPadrao: "5" },
  { numero: 25, descricao: "Papel contínuo: posição de corte (0~99mm)", valorPadrao: "35" },
  { numero: 26, descricao: "Papel contínuo: pré-definição de distância (0~1999)", valorPadrao: "16" },
  { numero: 27, descricao: "Largura da impressão dos relatórios (0~99mm)", valorPadrao: "54" },
  { numero: 28, descricao: "Tamanho da fonte para relatório (0: 10x18, 1: 18x26, 2: 26x34)" },
  { numero: 30, descricao: "Alimentação do sensor de posição (0~255) — não alterar" },
  { numero: 31, descricao: "Limitar ponto de barra do código de barras (0~9)", valorPadrao: "0" },
  { numero: 32, descricao: "Numerar largura do número do código de barras (0~19)", valorPadrao: "0" },
  { numero: 33, descricao: "Fonte de código de barras legível (0 grande, 1 muito pequeno, 2 médio)", valorPadrao: "0" },
  { numero: 34, descricao: "Anti estabilidade do peso enquanto imprime (0~19)", valorPadrao: "3" },
  { numero: 35, descricao: "Auto novo modo de linha (0 proibido, 1 permitido)", valorPadrao: "0" },
  { numero: 40, descricao: "Número da balança (0~9999999)", valorPadrao: "0" },
  { numero: 41, descricao: "Velocidade da comunicação RS232 (0:300 ... 9:115200)", valorPadrao: "9600" },
  { numero: 42, descricao: "Atualização automática por USB (0 proibido, 1 permitido)" },
  { numero: 43, descricao: "Modo ethernet (0 não conectado, 1 comum, 2 cliente)" },
  { numero: 46, descricao: "Tempo de leitura do USB (0~99, cada 10 = 1s)", valorPadrao: "10" },
  { numero: 47, descricao: "Alimentação do USB sempre ligado (0 desabilitado, 1 habilitado)" },
  {
    numero: 50,
    descricao: "Tipo de comunicação (0 cabo, 1 Wi-Fi STA, 2 Wi-Fi AP, 3 desativado, 4~7 prioridades mistas)",
  },
  { numero: 51, descricao: "Modo de segurança (0 desabilitado, 1 WEB, 2 WPA/WPA2)" },
  { numero: 52, descricao: "Opção de segurança (0 aberto, 1 chave compartilhada)" },
  { numero: 53, descricao: "SSID Wi-Fi" },
  { numero: 54, descricao: "Formato de etiqueta e código de barras (00~22, ver combinações SPEC/setor/PLU)" },
  { numero: 60, descricao: "Modo caixa (0 desativado, 3 habilitado)" },
  { numero: 65, descricao: "Imprimir novamente (0 proibido, 1 permitido)" },
  {
    numero: 67,
    descricao: "Número de tara (0 proibido, 1 permitido via teclado, 2 permitido seguindo o ponto do preço)",
  },
  {
    numero: 68,
    descricao: "Selecionar tara (0 apenas manual, 1 manual prioridade, 2 pré-determinada prioridade, 3 apenas pré-determinada)",
  },
  { numero: 69, descricao: "Retorna a zero para venda (0~4)" },
  { numero: 72, descricao: "Apagar dados de venda ao pressionar [modo de pesagem] (0 não apaga, 1 apaga)" },
  { numero: 75, descricao: "Proibido PLU (0 sem proibir, 1 peso, 2 peça, 3 todos)" },
  { numero: 76, descricao: "Vendas diversas de peso e peça proibidas (0~3)" },
  {
    numero: 78,
    descricao: "Modo automático - modo especial de venda (0 proibido, 1 lote, 2 empacotamento, 3 PLU travado, 4 impressão automática)",
  },
  { numero: 79, descricao: "Selecionar modo automático (0 proibido, 1 permitido)" },
  { numero: 80, descricao: "Cadastro de PLU por atalho (0 proibido, 2 permitido)" },
  { numero: 81, descricao: "Cadastro de tecla rápida por atalho (0 proibido, 1 permitido)" },
  { numero: 82, descricao: "Atalho para configuração do SPEC (0 proibido, 2 permitido)" },
  { numero: 89, descricao: "PLU Fast-Prog igual para PLU Prog (0 desabilitado, 1 habilitado)" },
  { numero: 97, descricao: "EAN13 fornecedor (0 proibido, 1 número, 2 número e caracteres)" },
  { numero: 100, descricao: "Arredondamento para venda de um único produto (0~11)" },
  { numero: 101, descricao: "Arredondamento do preço total para produtos acumulados (0~11)" },
  { numero: 104, descricao: "Padrão Data/Hora", valorPadrao: "4: DD/MM/AA 24h" },
  { numero: 105, descricao: "Impressão da data de validade (0~6, modo data/dias)" },
  { numero: 106, descricao: "Data de validade (dias, parte do SPEC 105)", valorPadrao: "0" },
  { numero: 118, descricao: "Recuperar venda (0~3)" },
  { numero: 121, descricao: "Método de processo com código do item = 0 (0~3)" },
  { numero: 135, descricao: "Login de operadores (0~6)" },
  { numero: 141, descricao: "Relatório de estoque (0 desabilitado, 1 habilitado)" },
  { numero: 149, descricao: "Mult chaves (0~3)" },
  { numero: 150, descricao: "Ethernet IP parte 1 (0~255)", valorPadrao: "192" },
  { numero: 151, descricao: "Ethernet IP parte 2 (0~255)", valorPadrao: "168" },
  { numero: 152, descricao: "Ethernet IP parte 3 (0~255)", valorPadrao: "0" },
  { numero: 153, descricao: "Ethernet IP parte 4 (0~255, 0 = DHCP)", valorPadrao: "150" },
  { numero: 154, descricao: "IP do PC parte 1 (apenas modo cliente)" },
  { numero: 155, descricao: "IP do PC parte 2 (apenas modo cliente)" },
  { numero: 156, descricao: "IP do PC parte 3 (apenas modo cliente)" },
  { numero: 157, descricao: "IP do PC parte 4 (apenas modo cliente)" },
  { numero: 158, descricao: "Gateway IP parte 1" },
  { numero: 159, descricao: "Gateway IP parte 2" },
  { numero: 160, descricao: "Gateway IP parte 3" },
  { numero: 161, descricao: "Gateway IP parte 4" },
  { numero: 162, descricao: "Máscara de sub-rede IP parte 1", valorPadrao: "255" },
  { numero: 163, descricao: "Máscara de sub-rede IP parte 2", valorPadrao: "255" },
  { numero: 164, descricao: "Máscara de sub-rede IP parte 3", valorPadrao: "255" },
  { numero: 165, descricao: "Máscara de sub-rede IP parte 4", valorPadrao: "0" },
  { numero: 166, descricao: "Server Mode Socket (0~65535)", valorPadrao: "33581" },
  { numero: 167, descricao: "Client Mode Socket (0~65535)", valorPadrao: "33582" },
  { numero: 168, descricao: "UDP Listen Socket (0~65535)", valorPadrao: "33583" },
  { numero: 169, descricao: "UDP Broadcast Socket (0~65535)", valorPadrao: "33584" },
  { numero: 170, descricao: "Primary DNS 1", valorPadrao: "8" },
  { numero: 171, descricao: "Primary DNS 2", valorPadrao: "8" },
  { numero: 172, descricao: "Primary DNS 3", valorPadrao: "8" },
  { numero: 173, descricao: "Primary DNS 4", valorPadrao: "8" },
  { numero: 180, descricao: "Display e impressão do ponto decimal (0 não, 1 baseado no SPEC 181)" },
  { numero: 190, descricao: "5° Display: PLU informação do display (0~3)" },
  { numero: 191, descricao: "5° Display: mensagem AD display (0~3)" },
  { numero: 192, descricao: "Informação no display matrix / 5° display (0~31, ver tabela)" },
  { numero: 193, descricao: "5° Display: no modo repouso (1 mensagem AD, 2 informação de acumulação)" },
  { numero: 194, descricao: "5° Display: PLU informação 1 (0 nome, 1~5 textos, 6 lote, 7 texto 7)" },
  { numero: 195, descricao: "5° Display: PLU informação 2 (0 nome, 1~5 textos, 6 lote, 7 texto 7)" },
  { numero: 247, descricao: "Função de manter senha (0 desabilitado, 2 exceto Admin, 3 todas)" },
  { numero: 250, descricao: "Modo de acumulação [Accu] igual à tecla [Imprimir] (0/1)" },
  { numero: 253, descricao: "Buscar PLU por código ao pressionar [PLU] (0 número, 1 código)" },
  { numero: 254, descricao: "Função auto [PLU] (0 desabilitado, 1~3 modos)" },
  { numero: 255, descricao: "Pesquisa automática [PLU] (0~11, dígitos/delay)" },
  {
    numero: 260,
    descricao: "Precisa senha de administrador em certos modos (soma: +1 venda, +2 prog, +4 conta, +8 gaveta, +16 preço unit.)",
    valorPadrao: "2",
  },
  { numero: 261, descricao: "PLU modo peso proibido no modo (soma 0~15)" },
  { numero: 262, descricao: "PLU modo peças proibido no modo (soma 0~15)" },
  { numero: 265, descricao: "Modo de impressão do mês (0 dígito, 1 caracteres)" },
  { numero: 266, descricao: "Filter Mode (0 padrão, 1 média mult, 2 média adequada)" },
];
